apiVersion: v2
name: gocron
description: Horizontally scalable gocron deployment with database-backed leader election
type: application
kubeVersion: '>=1.23.0-0'
version: 0.2.2
appVersion: '1.11.1'
keywords:
  - cron
  - scheduler
  - task
home: https://github.com/gocronx-team/gocron
icon: https://raw.githubusercontent.com/gocronx-team/gocron/master/web/gocronx-admin/public/favicon.ico
sources:
  - https://github.com/gocronx-team/gocron
maintainers:
  - name: gocronx-team
