{{- if not .Values.managed.existingSecret }}
{{- $name := include "gocron.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "gocron.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.managed.secretKeys.databasePassword }}: {{ .Values.db.password | quote }}
  {{ .Values.managed.secretKeys.authSecret }}: {{ .Values.managed.authSecret | quote }}
  {{ .Values.managed.secretKeys.encryptionKey }}: {{ .Values.managed.encryptionKey | quote }}
  {{ .Values.managed.secretKeys.adminPassword }}: {{ .Values.managed.admin.password | quote }}
{{- end }}
